name: "Hello World"
description: "Greet someone and record the time"
inputs:
  repository:
    description: "the repo where the packages resides"
    required: true
  directory:
    description: "the folder where package.json resides that we want to checked for versions"
    required: true
  ref:
    description: "the tag ref to checkout inside the repo"
    required: true
  token:
    description: "github token with access rights to the repo"
    required: true
outputs:
  newer: # id of output
    description: "true if package is newer then latest package of the same name in the repository"
runs:
  using: "node12"
  main: "dist/index.js"
